pipeline {
    agent any

    parameters {
        choice(
            name: 'inventory',
            choices: ['dev', 'uat'],
            description: 'Select the deployment environment'
        )

        string(
            name: 'tagging',
            defaultValue: '',
            description: 'Ansible tag to run'
        )
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'echo "Building Stage"'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'echo "Testing Stage"'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh "ansible-playbook -i inventory/${params.inventory} playbooks/site.yml --tags ${params.tagging}"
                }
            }
        }
    }
}
